name: "Run a docker-trestle command"
description: "Sets up workspace for running a single command in docker-trestle"
inputs:
  tag:
    description: docker-trestle tag to use. Defaults to latest
    required: false
    default: latest
  cmd:
    description: Command to run within docker-trestle
    required: true
runs:
  using: "composite"
  steps:
    - name: Enable writing to trestle directories
      shell: bash
      run: chmod -R a+w $GITHUB_WORKSPACE/doc/compliance/oscal

    - name: Run cmd
      shell: bash
      run: docker run -v $GITHUB_WORKSPACE/doc/compliance/oscal:/app/docs:rw ghcr.io/gsa-tts/trestle:latest ${{ inputs.cmd }}
