name: Compile assets for deploy
description: Restore a deployed asset cache, precompile, and clean
inputs:
  rails_env:
    description: RAILS_ENV to set.
    required: true
  fail_on_missing_cache:
    description: Whether to fail the action on a missing cache
    required: true
  save_cache:
    description: Whether to save the compiled assets to a cache
    required: false
    default: false
runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-languages

    - name: Restore asset cache
      uses: actions/cache/restore@v4
      with:
        key: ${{ inputs.rails_env }}-assets
        fail-on-cache-miss: ${{ inputs.fail_on_missing_cache }}
        path: |
          public/assets
          app/assets/builds
          app/javascript/generated

    - name: Precompile assets
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        SECRET_KEY_BASE_DUMMY: 1
      shell: bash
      run: ./bin/rake assets:precompile

    - name: list asset timestamps
      shell: bash
      run: ls -lh public/assets

    - name: Clean old assets
      env:
        RAILS_ENV: ${{ inputs.rails_env }}
        SECRET_KEY_BASE_DUMMY: 1
      shell: bash
      run: ./bin/rake assets:clean

    - name: Save cache
      if: ${{ inputs.save_cache }}
      uses: actions/cache/save@v4
      with:
        key: ${{ inputs.rails_env }}-assets-${{ hashFiles('public/assets/.manifest.json') }}
        path: |
          public/assets
          app/assets/builds
          app/javascript/generated
