name: Deploy egress proxy
description: Set egress space security groups
inputs:
  cf_space:
    description: The space the target app exists in.
    required: true
runs:
  using: composite
  steps:
    - name: Install cf-cli
      shell: bash
      run: |
        curl -A "cg-deploy-action" -v -L -o cf-cli_amd64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=v8&source=github'
        sudo dpkg -i cf-cli_amd64.deb
    - name: Login to cf-cli
      shell: bash
      run: |
        cf api api.fr.cloud.gov
        cf auth
    - name: Set proper space egress rules
      shell: bash
      run: |
        ./bin/ops/set_space_egress.sh -s ${{ inputs.cf_space }} -t
        ./bin/ops/set_space_egress.sh -s ${{ inputs.cf_space }}-egress -p
