name: Run Auditree Checks

on:
  workflow_dispatch:
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at 11am UTC every day (6am EST / 7am EDT)
    - cron: '0 11 * * *'

jobs:
  run_auditree:
    name: Fetch and check auditree evidence
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Fetch evidence
        uses: ./.github/actions/auditree-cmd
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.AUDITREE_GITHUB_TOKEN }}
        with:
          cmd: fetch
          email: "ryan.ahearn@gsa.gov"

      - name: Check evidence
        uses: ./.github/actions/auditree-cmd
        env:
          GITHUB_TOKEN: ${{ secrets.AUDITREE_GITHUB_TOKEN }}
        with:
          tag: 20240912
          cmd: -o check
          email: "ryan.ahearn@gsa.gov"

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: auditree_assessment_results
          path: tmp/auditree/auditree.json
