name: rspec tests

on: [pull_request]

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: continuous_monitoring_test
          POSTGRES_USER: cidbuser
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup-project
        with:
          rails_env: test

      - name: Run rspec
        env:
          DATABASE_URL: ${{ steps.setup.outputs.database_url }}
          rspec_oscal_output: tmp
        run: bundle exec rspec

      - name: Save assessment results
        uses: actions/upload-artifact@v4
        with:
          name: continuous_monitoring_assessment
          path: tmp/oscal
