name: Run Terraform plan in production

on:
  pull_request:
    branches: [ production ]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform plan
    runs-on: ubuntu-latest
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: terraform

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        env:
          TF_VAR_cf_user: ${{ secrets.CF_USERNAME }}
          TF_VAR_cf_password: ${{ secrets.CF_PASSWORD }}
          TF_VAR_rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}
        with:
          path: terraform
          var_file: terraform/production.tfvars
          backend_config: >
            access_key=${{ secrets.TERRAFORM_STATE_ACCESS_KEY }}
            secret_key=${{ secrets.TERRAFORM_STATE_SECRET_ACCESS_KEY }}
            bucket=${{ secrets.TERRAFORM_STATE_BUCKET_NAME }}
            key=terraform.tfstate.production
